version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gazdhirlevel_postgres
    environment:
      POSTGRES_DB: gazdhirlevel
      POSTGRES_USER: gazdhir_user
      POSTGRES_PASSWORD: gazdhir_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gazdhir_user -d gazdhirlevel"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: gazdhirlevel_app
    environment:
      DATABASE_URL: postgresql://gazdhir_user:gazdhir_pass@postgres:5432/gazdhirlevel
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TEST_MODE: ${TEST_MODE:-false}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    restart: unless-stopped

volumes:
  postgres_data: